[server]
address = "127.0.0.1"
port = 8510
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
